import base64
import json
import cv2
import numpy as np
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
from engine.pose_engine import PoseEngine
from engine.llm_feedback import generate_feedback, generate_session_feedback

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

engine = PoseEngine()


def decode_frame(data: str):
    """Decode a base64 JPEG string into an OpenCV frame."""
    img_bytes = base64.b64decode(data)
    img_arr   = np.frombuffer(img_bytes, dtype=np.uint8)
    return cv2.imdecode(img_arr, cv2.IMREAD_COLOR)


# ── Real time pose endpoint 
@app.websocket("/ws/pose")
async def websocket_pose(websocket: WebSocket):
    await websocket.accept()
    print("[/ws/pose] Frontend connected")
    try:
        while True:
            data = await websocket.receive_text()

            # Frontend JSON: {image, mode, target_reps}
            try:
                msg = json.loads(data)
                image_b64   = msg.get("image", "")
                mode        = msg.get("mode", "squat")
                target_reps = msg.get("target_reps", 12)
            except (json.JSONDecodeError, AttributeError):
                # Fallback
                image_b64   = data
                mode        = "squat"
                target_reps = 12

            frame = decode_frame(image_b64)
            if frame is not None:
                analysis, landmarks = engine.process_frame(frame, mode)
                await websocket.send_json({
                    "angle":      round(analysis.get("angle", 0), 1),
                    "status":     analysis.get("status", ""),
                    "count":      analysis.get("count", 0),
                    "timer":      analysis.get("timer", 0),
                    "side_view":  analysis.get("side_view", True),
                    "error_type": analysis.get("error_type", None),
                    "last_rep":   analysis.get("last_rep", None),
                    "landmarks":  landmarks,
                })
    except WebSocketDisconnect:
        print("[/ws/pose] Client disconnected")
    except Exception as e:
        print(f"[/ws/pose] Error: {e}")


# ── Session feedback endpoint 
class UserProfile(BaseModel):
    height: Optional[int] = None
    weight: Optional[int] = None
    age:    Optional[int] = None

class SessionFeedbackRequest(BaseModel):
    exercise:    str
    rep_count:   int
    error_count: int
    rep_history: List[dict] = []
    logs:        List[dict] = []
    user_profile: Optional[UserProfile] = None

@app.post("/session/feedback")
async def session_feedback(req: SessionFeedbackRequest):
    """
    Called by the frontend after a training session ends.
    Accepts session summary data and returns AI coaching feedback
    generated by the backend using Gemini — no frontend API key needed.
    """
    feedback = generate_session_feedback(req.model_dump())
    print(f"[/session/feedback] exercise={req.exercise} reps={req.rep_count} errors={req.error_count}")
    return {"feedback": feedback}


# test
@app.websocket("/ws/session")
async def websocket_session(websocket: WebSocket):
    await websocket.accept()
    print("[/ws/session] Client connected")

    frames         = []
    session_active = False

    try:
        while True:
            data = await websocket.receive_text()

            try:
                msg      = json.loads(data)
                msg_type = msg.get("type")

                if msg_type == "start":
                    frames         = []
                    session_active = True
                    print("[/ws/session] Session started")
                    await websocket.send_json({"status": "recording"})

                elif msg_type == "stop":
                    session_active = False
                    print(f"[/ws/session] Session stopped — {len(frames)} frames buffered")

                    if not frames:
                        await websocket.send_json({
                            "type":     "final_result",
                            "status":   "error",
                            "feedback": "No frames received. Please try again.",
                        })
                        continue

                    session_data     = engine.process_session(frames)
                    summary          = engine.summarize_session(session_data)
                    summary["feedback"] = generate_feedback(summary)

                    print(f"[/ws/session] Result: reps={summary['rep_count']} score={summary['score']}")
                    await websocket.send_json(summary)

            except (json.JSONDecodeError, KeyError):
                if session_active:
                    frame = decode_frame(data)
                    if frame is not None:
                        frames.append(frame)

    except WebSocketDisconnect:
        print("[/ws/session] Client disconnected")
    except Exception as e:
        print(f"[/ws/session] Error: {e}")
